let rp="Report Card";
console.log(rp);
console.log();
let name="Name: Sweta Maurya";
console.log(name);
console.log();
let School="School: Ram Dev Maurya Balika Inter Collge";
console.log(School);
console.log();
let Grade="Grade: A+";
console.log(Grade);
console.log();
let Section="Section: B";
console.log(Section);
console.log();
let RollNo="RollNo: 3";
console.log(RollNo);
console.log();
let Subject="Subject";
console.log(Subject);
console.log();
let Maths="Maths: 85";
console.log(Maths);
console.log();
let English="English: 80";
console.log(English);
console.log();
let Science="Science: 81";
console.log(Science);
